### PR TITLE
Add dashboard notice and improve upsell notice design

### LINKED ISSUE #194: recommend neve + otter
@selul I saw here we recommend advanced css, maybe we can redo that part and add some blocks where we mention some of our main products as cards + maybe if we want 2-3 tutorials that we think are relevant : https://vertis.d.pr/0r4LDH . 

Since that space is created by our plugin, I don't think we're messing with the user experience. Not sure if is worth considering a notice in the wp-admin/nav-menus.php that we recommend to use it with Neve.

### PR DESCRIPTION
**Pull request by girishpanchal30**
Close #194

### CODE REVIEW

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and the upsell works fine 👍 

Only one thing, i can't find any **Otter blocks** upsell, did we stick to only recommending Neve?
cc: @selul

**Comment by selul** [comment]
@irinelenache no, we should have both.

**Comment by girishpanchal30** [comment]
@selul Okay, So I need to add the same notice for Otter blocks right? But I think missing otter block part in design
Can you please check here: https://www.figma.com/file/lfDtHB51hvKH0TBBIkJfZp/Menu-Icons?node-id=1%3A8

**Comment by mghenciu** [comment]
Here is how the Otter section would look.
[Figma file](https://www.figma.com/file/lfDtHB51hvKH0TBBIkJfZp/Menu-Icons?node-id=132%3A6)
Preview - Otter card
Also made a copy for the thumbnails images without shadow, in Figma - if needed.

And as mentioned, at the end of [this comment](https://github.com/Codeinwp/wp-menu-icons/issues/194#issuecomment-974090037), we should have just one card displayed at a time. And after each week or 2 weeks, automatically reverse them, and so on.

**Example**:
- 1 user installed WP Menu Icons and sees there Neve card, after 2 weeks, he would see there Otter card. Again after 2 weeks, there will be Neve again - and keep this loop going every 2 weeks.
- 1 user installed WP Menu Icons and sees there Otter card, after 2 weeks, he would see there Neve card. Again after 2 weeks, there will be Otter card - an so on every 2 weeks.

Let me know if there are questions during the process @girishpanchal30 .
Thank you!

**Comment by girishpanchal30** [comment]
> Also made a copy for the thumbnails images without shadow, in Figma - if needed.
@mghenciu Can you provide me without shadow thumbnails images for otter block upsell notices?
Thanks

**Comment by mghenciu** [comment]
> > Also made a copy for the thumbnails images without shadow, in Figma - if needed.
> 
> @mghenciu Can you provide me without shadow thumbnails images for otter block upsell notices? Thanks

The frames are on the right side in Figma, @girishpanchal30 .
Screenshot 2022-03-02 at 14 26 53

And I guess you'll add the shadows with CSS.
Ping me if it doesn't work or something.

**Comment by girishpanchal30** [comment]
@mghenciu I have managed to set image @irinelenache Can you please retest?
Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Tested again and now everything works fine, thank you 🚀

**Pull request merged**
