### PR TITLE
Upgrade font awesome library

### LINKED ISSUE #201: Font Awesome 6.0
The newest version of Font Awesome adds a smorgasbord of icons, including one authors have been clamoring for: Goodreads.  It also adds TikTok, which I can see just about any site using these days.

Could I please ask for consideration to have the version of Font Awesome utilized within the plugin updated to version 6.0?

Thank you!

-Ben

### PR DESCRIPTION
**Pull request by girishpanchal30**
Close #201, #216

### CODE REVIEW

**Comment by irinelenache** [comment]
@girishpanchal30 I can't make the new icons work, please let me know if i missed anything. I tried to add them in more ways https://vertis.d.pr/9VWubn and they will appear as empty when i try to add them (both in settings and frontend) https://vertis.d.pr/mayOGX

**Comment by girishpanchal30** [comment]
@irinelenache Can you please share your test instance details here?

**Comment by irinelenache** [comment]
Sure,
```
 Admin area URL: https://otter-fse.s2-tastewp.com/wp-admin 
 Username: irinel 
 Password: wo1Qr78VYus 
```

**Comment by girishpanchal30** [comment]
@irinelenache I think you have tested with Pro icons, Can you please check with Free icons here: https://fontawesome.com/search?m=free

**Comment by girishpanchal30** [comment]
@irinelenache https://www.awesomescreenshot.com/image/31202424?key=4ecff8ce3569b64a2b370fa05aceab34

**Comment by irinelenache** [comment]
@girishpanchal30 I used icons from the link you provided, but all of them appear as pro actually, even if the search is filtered for Free. I also tried with Brands icons and they still don't work.

Can you show me a video of making them work or you can send here some free icons that i will use?

**Comment by girishpanchal30** [comment]
@irinelenache I'm not sure why the filter listed pro icons. but font awesome provides only 2016 icons.
Ref: https://tinyurl.com/2mwwjqsf

**Comment by irinelenache** [comment]
@girishpanchal30 Managed to test it on a fresh instance and it seems to work, found some problems though:

- [ ] Icons work only when they are added as **solid** (for example `fa-solid fa-baseball`). If i add them as **regular** they won't load at all and if i add them as **thin**, they will look like this https://vertis.d.pr/mSm1Hi
- [ ] Some multi word icons don't work, i don't know exactly why is that
Multi word icons that work: `fa-solid fa-bed-pulse , fa-book-journal-whills , fa-solid fa-bezier-curve`
Multi word icons that don't work: `fa-solid fa-bitcoin-sign , fa-solid fa-bowl-rice , fa-solid fa-baseball-bat-ball`

You can check the issues on this instance:
```
 Admin area URL: https://menu-icons.s2-tastewp.com/wp-admin 
 Username: irinel 
 Password: RBB1asmp81E 
```

**Comment by girishpanchal30** [comment]
@irinelenache Fixed above mentioned issue, Please check with the latest commit.

**Comment by irinelenache** [comment]
@girishpanchal30 The second issue is fixed, thank you 👍 But for the first one, the problem is still happening

**Comment by girishpanchal30** [comment]
@irinelenache I think the `fa-solid fa-baseball` free icon is available for the solid category only. you can check here: https://fontawesome.com/search?q=baseball&m=free&s=regular

**Comment by irinelenache** [comment]
@girishpanchal30 Thank you, i realised **thin** and **light** work only in the pro version. This is good to merge now 🚀

**Pull request merged**
