### PR TITLE
Add font awesome 5 support

### LINKED ISSUE #130: Font Awesome 5.0
We should include Font Awesome 5.0 icons. @abaicus

### PR DESCRIPTION
**Pull request by girishpanchal30**
Close #130

### CODE REVIEW

**Comment by irinelenache** [comment]
@girishpanchal30 Tested this feature:

- [ ] When updating from the latest version of the plugin, some menu items aren't visible in dashboard anymore and they don't work at all in frontend
menu before update: https://vertis.d.pr/47IFKB
menu after update: https://vertis.d.pr/9eJHH6
frontend after update: https://vertis.d.pr/vn8k0U

Also how the filter provided should be used? I tried to test it but i couldn't make it work.

**Comment by girishpanchal30** [comment]
@irinelenache Fixed display icon issue when updating from the latest version of the plugin.

For filter:

1. Add filter in your current active theme functions.php file
2. Go to wp-admin/nav-menus.php
3. Open any menu item and click on Icon: select button.
4. Go to Font Awesome Tab and search your new icon name - https://tinyurl.com/y4yvdjac.

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Now the icons work fine in frontend after updating, but there is still a problem in dashboard. Encountered it with 2 icons (Safari, Bitcoin)
dashboard: https://vertis.d.pr/4Av0Bg
frontend: https://vertis.d.pr/39FqaK

Followed your steps for the filter and it works fine 👍

**Comment by girishpanchal30** [comment]
@irinelenache Fixed above issue please retest again.

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Now the issue is fixed, thanks 🚀

**Comment by cristian-ungureanu** [comment]
@girishpanchal30 I don't think this method of adding icons would work. As an end-user, it would be hard for me to connect to FTP, find the file and add something to an array every time I want another icon.

What I would do here is to create another category named Font Awesome 5 and load the new icons as we do with fa4
Screenshot 2021-12-17 at 15 33 12

We can avoid conflicts by not allowing users to use both fa5 and fa4 icon sets at the same time ... or at least display a notice somewhere in the dashboard that the icons might not work well together.

**Comment by girishpanchal30** [comment]
@cristian-ungureanu  do you think it would be good if we register the fa5 icon as a new category? Because we already have 300+ icons added in our plugin.
As of now, I have added backward compatibility for fa5 icon or if user want to add more icon then he can use the filter.

Thanks

**Comment by cristian-ungureanu** [comment]
@girishpanchal30 if adding a new category for FA5 is a bad idea, at least let's provide a way for the users to add fa5 classes in a field somewhere in the plugin. We can have a field where the customer adds all the classes that are needed separated with ",", then those icons will be available as the rest of the icons.
For example, we can have something like this: https://d.pr/pXxMou ... the location of that field can be changed and can be placed in another place, maybe after the whole menu setting.
Then we can use the content of that textarea as input for the filter we've added.

**Comment by girishpanchal30** [comment]
@cristian-ungureanu Yes, we can add a textarea field in the plugin settings panel. there are no hooks to add a field in you have mentioned location.

Ref - https://tinyurl.com/y3hsav6r

Thanks

**Comment by girishpanchal30** [comment]
@irinelenache Can you retest again? I have added a new field to add more FA5 icons
Ref - https://tinyurl.com/y3hsav6r

cc @cristian-ungureanu 
Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Tested again and it works fine for me 👍 
Note: After adding the classes and clicking on Save settings the menus page `../wp-admin/nav-menus.php` should be refreshed for the icons to show up in icons list

If @cristian-ungureanu approves it, it can be moved to **Ready to merge**

**Comment by irinelenache** [comment]
@girishpanchal30 Tested again and everything works fine 👍

**Comment by mghenciu** [comment]
Hi @girishpanchal30,

I've seen that you've requested edit acces on one of Menu Icon figma files.
Unfortunately we don't have any available editor seats in our Figma plan, but please let me know if you need help with something in Figma.

Have a great day.

**Comment by girishpanchal30** [comment]
@mghenciu I need help here #194
Thanks

**Pull request merged**
